version: '3.4'
services:
  rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        volumes:
            - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
            - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
            - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        ports:
            - 5672:5672
            - 15672:15672
  CarService:
    image: carservice:latest
    build:
      context: .
      dockerfile: src/services/Car-Service/Car-Service/Dockerfile
    container_name: CarService
  LoggingService:
    image: loggingservice:latest
    build:
      context: .
      dockerfile: src/services/LoggingService/LoggingService/Dockerfile
    container_name: LoggingService
  LocationService:
    image: locationservice:latest
    build:
      context: .
      dockerfile: src/services/Location Service/Location Service/Dockerfile
    container_name: LocationService
  SurveyService:
    image: surveyserviceapp:latest
    build:
      context: .
      dockerfile: src/services/SurveyServiceApp/Dockerfile
  PickupDropoffService:
    image: pickupdropoffservice:latest
    build:
        context: .
        dockerfile: src/services/PickupDropoffService/Dockerfile
    container_name: PickupDropoffService
  CustomerService:
    image: customerservice:latest
    build:
        context: .
        dockerfile: src/services/CustomerService/Dockerfile
    container_name: CustomerService
  api.gateway:
    image: apigateway:latest
    build:
      context: .
      dockerfile: src/gateways/API.Gateway/Dockerfile
    container_name: apigateway
  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    container_name: consul
  