version: '3.4'
services:
  CarService:
    image: carservice:latest
    build:
      context: .
      dockerfile: src/services/Car-Service/Car-Service/Dockerfile
    container_name: CarService
  LocationService:
    image: locationservice:latest
    build:
      context: .
      dockerfile: src/services/Location Service/Location Service/Dockerfile
    container_name: LocationService
  SurveyService:
    image: surveyserviceapp:latest
    build:
      context: .
      dockerfile: src/services/SurveyServiceApp/Dockerfile
    container_name: SurveyService
  PickupDropoffService:
    image: pickupdropoffservice:latest
    build:
        context: .
        dockerfile: src/services/PickupDropoffService/Dockerfile
    container_name: PickupDropoffService
  api.gateway:
    image: apigateway:latest
    build:
      context: .
      dockerfile: src/gateways/API.Gateway/Dockerfile
    container_name: apigateway
  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    container_name: consul