version: '3.4'
services:
  CarService:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ServiceConfig__serviceDiscoveryAddress=http://consul:8500
      - ServiceConfig__serviceAddress=http://CarService:80
      - ServiceConfig__serviceName=CarService
      - ServiceConfig__serviceId=1
    ports:
      - "5005:80"
    
  LocationService:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ServiceConfig__serviceDiscoveryAddress=http://consul:8500
      - ServiceConfig__serviceAddress=http://LocationService:80
      - ServiceConfig__serviceName=LocationService
      - ServiceConfig__serviceId=1
    ports:
      - "5006:80"
  SurveyService:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ServiceConfig__serviceDiscoveryAddress=http://consul:8500
      - ServiceConfig__serviceAddress=http://SurveyService:80
      - ServiceConfig__serviceName=SurveyService
      - ServiceConfig__serviceId=1
    ports:
      - "5007:80"
  PickupDropoffService:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ServiceConfig__serviceDiscoveryAddress=http://consul:8500
      - ServiceConfig__serviceAddress=http://PickupDropoffService:80
      - ServiceConfig__serviceName=PickupDropoffService
      - ServiceConfig__serviceId=1
    ports:
      - "5008:80"
  api.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8002:80"
  consul:
    ports:
      - "8500:8500"